DeathClearExp: true
Dispense:
  WitherSkull: false
NewPlayer:
  paper: true
ProtectVillage:
  zombie: false
  lightning: true
EntityBreed:
  Villager: false
EntitySpawn:
  IronGlorm: 0.2
  IronGlorm_Count: 1000
  ZombifiedPiglin: 0.0
  ZombifiedPiglin_Count: 1000
  ZombifiedPiglin_GoldenSword: false
SuicideCoolDown: 60
SpawnerChange: false
rule:
- 伺服器規定
StrippedLog: false
PVPCoolDown: 30
NetheriteEquipment: false
RaidItem: false
PVPChange: true