main: me.miunapa.paserverfeature.Main
name: PAServerFeature
version: 0.2
api-version: 1.14

commands:
  paf:
    description: PAServerFeature 功能
    usage: /paf
    permission: feature.paf

permissions:
  feature.paf:
    default: op