main: me.miunapa.paserverfeature.Main
name: PA_ServerFeature
version: 1.10.1
api-version: 1.16

commands:
  suicide:
    description: 自殺
    usage: /suicide
    permission: paserverfeature.suicide
  hat:
    description: 戴帽子
    usage: /hat
    permission: paserverfeature.hat
  getip:
    description: 取得玩家IP(必須在線上)
    usage: /getip
    permission: paserverfeature.getip
  rule:
    description: 伺服器規定
    usage: /rule
    permission: paserverfeature.rule
  rules:
    description: 伺服器規定
    usage: /rules
    permission: paserverfeature.rule
  signature:
    description: 地圖複製
    usage: /signature
    permission: paserverfeature.signature
  pvp:
    description: pvp指令
    usage: /pvp
    permission: paserverfeature.pvp
  lc:
    description: 更改鎖箱子指令
    usage: /lc
    permission: paserverfeature.lc
  invisible:
    description: 隱形3分鐘
    usage: /invisible
    permission: paserverfeature.invisible
  es:
    description: 查詢EntitySpawn
    usage: /es
    permission: paserverfeature.entityspawn
  roll:
    description: roll
    usage: /roll
    permission: paserverfeature.roll
permissions:
  paserverfeature.hat:
    default: true
  paserverfeature.suicide:
    default: op
  paserverfeature.rule:
    default: true
  paserverfeature.signature:
    default: true
  paserverfeature.signatureforce:
    default: op
  paserverfeature.pvp:
    default: true
  paserverfeature.pvpbypass:
    default: op
  paserverfeature.lc:
    default: op
  paserverfeature.invisible:
    default: op
  paserverfeature.entityspawn:
    default: op
  paserverfeature.roll:
    default: true