main: me.miunapa.paserverfeature.Main
name: PAServerFeature
version: 0.3
api-version: 1.14

commands:
  paf:
    description: PAServerFeature 功能
    usage: /paf
    permission: paserverfeature.paf
  hat:
    description: 戴帽子
    usage: /hat
    permission: paserverfeature.hat
permissions:
  paserverfeature.paf:
    default: op
  paserverfeature.hat:
    default: true