main: me.miunapa.pamainserverfeature.Main
name: PAMainServerFeature
version: 0.4.4
api-version: 1.14

commands:
  suicide:
    description: 自殺
    usage: /suicide
    permission: pamainserverfeature.suicide
  hat:
    description: 戴帽子
    usage: /hat
    permission: pamainserverfeature.hat
  getip:
    description: 取得玩家IP(必須在線上)
    usage: /getip
    permission: pamainserverfeature.getip
permissions:
  pamainserverfeature.paf:
    default: op
  pamainserverfeature.hat:
    default: true
  pamainserverfeature.getip:
    default: op
  pamainserverfeature.suicide:
    default: true
  pamainserverfeature.bypasslimit:
    default: op