main: me.miunapa.paserver.Main
name: PAServer
version: 0.2
api-version: 1.14

commands:
  paf:
    description: PAServer 功能
    usage: /paf
    permission: paserver.paf
  getloc:
    description: 獲取
    usage: /getloc
    permission: paserver.getloc

permissions:
  paserver.paf:
    default: op
  paserver.getloc:
    default: op