main: me.miunapa.paserverfeature.Main
name: PAServerFeature
version: 0.6.1
api-version: 1.15

commands:
  suicide:
    description: 自殺
    usage: /suicide
    permission: paserverfeature.suicide
  hat:
    description: 戴帽子
    usage: /hat
    permission: paserverfeature.hat
  getip:
    description: 取得玩家IP(必須在線上)
    usage: /getip
    permission: paserverfeature.getip
  rule:
    description: 伺服器規定
    usage: /rule
    permission: paserverfeature.rule
  rules:
    description: 伺服器規定
    usage: /rules
    permission: paserverfeature.rule
  signature:
    description: 地圖複製
    usage: /signature
    permission: paserverfeature.signature
permissions:
  paserverfeature.hat:
    default: true
  paserverfeature.getip:
    default: op
  paserverfeature.suicide:
    default: true
  paserverfeature.bypasslimit:
    default: op
  paserverfeature.rule:
    default: true
  paserverfeature.signature:
    default: true