main: me.miunapa.paserverfeature.Main
name: PAServerFeature
version: 0.2
api-version: 1.14

commands:
  paf:
    description: PAServerFeature 功能
    usage: /paf
    permission: paserverfeature.paf
  getloc:
    description: 獲取
    usage: /getloc
    permission: paserverfeature.getloc

permissions:
  paserverfeature.paf:
    default: op
  paserverfeature.getloc:
    default: op